#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

jupyter nbextension install https://rawgit.com/jfbercher/latex_envs/master/latex_envs.zip  --user
jupyter nbextension enable latex_envs/latex_envs	
